//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger_NGO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.DontationDetails = new HashSet<DontationDetail>();
        }
    
        public int Id { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> ResId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<DontationDetail> DontationDetails { get; set; }
    }
}
